### ISSUE TITLE
The test suite is broken.

### ISSUE THREAD

**Issue by t2013anurag** [kekik/rails-pretty-logger#9]
```An error occurred while loading ./spec/class/pretty_logger_spec.rb.
Failure/Error: require File.expand_path('../../config/environment.rb', __FILE__)

LoadError:
  cannot load such file -- /Users/anuragtiwari/work/rails-pretty-logger/config/environment.rb
# ./spec/rails_helper.rb:4:in `require'
# ./spec/rails_helper.rb:4:in `<top (required)>'
# ./spec/class/pretty_logger_spec.rb:1:in `require'
# ./spec/class/pretty_logger_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/controllers/dashboards_controller_spec.rb.
Failure/Error: require File.expand_path('../../config/environment.rb', __FILE__)

LoadError:
  cannot load such file -- /Users/anuragtiwari/work/rails-pretty-logger/config/environment.rb
# ./spec/rails_helper.rb:4:in `require'
# ./spec/rails_helper.rb:4:in `<top (required)>'
# ./spec/controllers/dashboards_controller_spec.rb:1:in `require'
# ./spec/controllers/dashboards_controller_spec.rb:1:in `<top (required)>'
No examples found.


Finished in 0.0005 seconds (files took 0.10469 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples```


On looking through the code found that no valid environments have been defined.

**Comment by MehmetCelik4** [comment]
Hello, thank you for your feedback, i should put this to read.me.

i used engine for building this project, so in order to pass the tests, you should add a dummy rails app into spec folder.

easiest way is:
`rails plugin new rails-pretty-logger --mountable`
then 
copy dummy folder from test/dummy  into rspec folder after this pass should pass.
